services:
  - type: web
    name: mindscape
    env: python
    buildCommand: |
      pip install -r requirements.txt
      rm -rf migrations
      flask db init
      flask db migrate -m "initial migration"
      flask db upgrade
      python seed_db.py
    startCommand: gunicorn "run:app" --timeout 120 --workers 4 --worker-class gevent
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mindscape-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: mindscape-db
    databaseName: mindscape
    user: mindscape
    plan: free 