"""Initial migration with assessment types

Revision ID: 80391649d7f5
Revises: 
Create Date: 2025-04-23 09:14:46.362005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80391649d7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment', sa.Column('assessment_type', sa.String(length=50), nullable=False))
    op.add_column('question', sa.Column('assessment_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'assessment_type')
    op.drop_column('assessment', 'assessment_type')
    # ### end Alembic commands ###
